version: '2'
services:
  server:
    build: .
    ports:
     - "1022:22"
     - "1080:80"
     - "1443:443"
     - "15432:5432"
    volumes:
      - ./data:/data

# docker-compose -f docker-compose.dev.yml up --build