version: '2'
services:
  server:
    build: .
    environment:
      ON_START_BASH_SCRIPT_PATH: "/home/webapp/webapp/current/sidekiq_start.sh"
    ports:
     - "1022:22"
     - "1080:80"
    volumes:
      - ./data/webapp:/home/webapp/webapp
      - ./data/ssh:/home/webapp/.ssh

# docker-compose -f docker-compose.dev.yml up --build