version: '2'
services:
  server:
    build: .
    ports:
     - "3322:22"
     - "8080:80"
     - "8443:443"
     - "15432:5432"
#    volumes:
#      - ./data:/data

# docker-compose -f docker-compose.dev.yml up --build