version: '2'
services:
  server:
    image: ipepe/pnpr
    restart: always
    ports:
     - "3322:22"
     - "80:80"
     - "443:443"
     - "5432:5432"
    volumes:
      - ./data:/data

# docker-compose up