version: '2'
services:
  server:
    image: ipepe/pnpr:ruby-2.3.1
    restart: always
    environment:
      ON_START_BASH_SCRIPT_PATH: "/home/webapp/webapp/current/sidekiq_start.sh"
    ports:
     - "3322:22"
     - "80:80"
     - "5432:5432"
    volumes:
      - ./data:/data
    links:
      - postgres_db

  postgres_db:
    image: postgres:14
    expose:
      - 5432

# docker-compose down
# docker-compose pull
# docker-compose up