version: '2'
services:
  server:
    image: ipepe/pnpr:v2-staging-ruby-2.7.5
    environment:
      PGPASSWORD: Password1
    links:
      - postgres_db
    ports:
      - "1022:22"
      - "1080:80"
    network_mode: bridge
    volumes:
      - ./data/webapp:/home/webapp/webapp
      - ./data/ssh:/home/webapp/.ssh

  postgres_db:
    image: postgres:14
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: Password1
    expose:
      - 5432
    network_mode: bridge
    volumes:
      - ./data/db:/var/lib/postgresql/data

# docker-compose -f docker-compose.staging.yml up --build