version: '3.2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=staging
        - RUBY_VERSION=2.3.1
        - NODE_MAJOR_VERSION=10
    environment:
      POSTGRES_PASSWORD: Password1
      RAILS_ENV: 'staging'
    ports:
      - "1022:22"
      - "1080:80"
      - "9149:9149"
    volumes:
      - ./data/webapp:/home/webapp/webapp
      - ./data/ssh:/home/webapp/.ssh
    links:
      - postgres_db
    network_mode: bridge

  postgres_db:
    network_mode: bridge
    image: postgres:15
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: Password1
    expose:
      - 5432
#    volumes:
#      - ./data/db:/var/lib/postgresql/data

# docker-compose -f docker-compose.dev.yml up --build