version: '2'
services:
  server:
    image: ipepe/pnpr:ruby-2.3.1
    restart: always
    ports:
     - "3322:22"
     - "80:80"
     - "5432:5432"
    volumes:
      - ./data:/data

# docker-compose up