version: '2'
services:
  server:
    image: ipepe/pnpr:v2-staging
    ports:
      - "1022:22"
      - "1080:80"
    links:
      - postgres_db
    volumes:
      - ./data/webapp:/home/webapp/webapp
      - ./data/ssh:/home/webapp/.ssh

  postgres_db:
    image: postgres:14
    expose:
      - 5432

# docker-compose -f docker-compose.staging.yml up --build