version: '3.2'
services:
  server:
    image: ipepe/pnpr:v3-u2004-r2.3.1-n10-staging
    restart: always
    network_mode: bridge
    healthcheck:
      disable: true
    environment:
      PGPASSWORD: Password1
    links:
      - postgres_db
    ports:
      - "3322:22"
      - "3080:80"
    volumes:
      - ./data/webapp:/home/webapp/webapp
      - ./data/ssh:/home/webapp/.ssh
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:staging.example.org"

  postgres_db:
    network_mode: bridge
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: Password1
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/dbdumps:/dbdumps

# docker-compose -f docker-compose.staging.yml up --build