name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.0', '2.7']
        node-version: ['16', '14', '12']
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for ruby-${{ matrix.ruby-version }} and node-${{ matrix.node-version }}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
